### ISSUE TITLE
Starting two days ago, when starting Furdown, I do not get the furdown front page.

### ISSUE THREAD

**Issue by Thomas17830** [crouvpony47/furdown#10]
Click on Furdown and get the following response:
furdown 0.4.3.0
<github.com/crouvpony47> <crouvpony47.itch.io>
Checking authorization...
Found some cookies.
Does not seem to be authorized, showing login page

It then shows me the login page for FurAffinity.  I never get the front page for furdown with all the windows - such as section to download, where to download, etc.

**Comment by crouvpony47** [comment]
FA is currently under a moderately heavy DDoS attack, thus having Cloudflare's "I'm Under Attack" mode enabled. Simply taking some valid cookies and running with them seems to not be enough to convince it that you are a legit user. I'm currently unaware of any _reliable_ solution of this problem apart from waiting, but if you do, please let me know.

**Comment by crouvpony47** [comment]
Found a solution (or more precisely, an error in existing one that prevented it from working).

Please [check this release out](https://github.com/crouvpony47/furdown/releases/tag/v.0.4.4.0). If the problem persists, feel free to reopen this issue or create a new one.
