### ISSUE TITLE
keep getting error Unsuccessfull login atempt

### ISSUE THREAD

**Issue by AfxousaAjagara** [crouvpony47/furdown#11]
After login to FA, furdown says Not ahthorized! and get Unsuccessfull login atempt error.
Is there any solution for this? or maybe how to give you information for debug?

**Comment by crouvpony47** [comment]
The FA page template has changed once again. I am investigating what exactly has broken, and working on the fix.

**Comment by crouvpony47** [comment]
Authorization has been fixed in [v.0.4.5.0](https://github.com/crouvpony47/furdown/releases/tag/v.0.4.5.0).

Thank you for reporting this issue!
