### ISSUE TITLE
Microsoft Defender SmartFilter: "This app might harm your device"

### ISSUE THREAD

**Issue by Youboontoo** [crouvpony47/furdown#14]
`Microsoft Defender SmartScreen reported that this app is not commonly downloaded or is not signed by its publisher.

Name: furdown.exe
Publisher: Unknown`

**Comment by Youboontoo** [comment]
Looks like VirusTotal marks it as safe, but seeing that error may turn users away from your program.
https://www.virustotal.com/gui/file/5eb064a46282f5f38cf9317cf969a7566c0660701cd10acf6790ffdaf4bfa75b

**Comment by crouvpony47** [comment]
Thank you for your interest in this project!
Whether or not you'll get a SmartScreen warning depends on the number of people downloading a particular app.
With about 250 downloads per build, I can't expect this app to be deemed popular enough. Code signing might make this message less frightening, but this will require considerable monetary investment on my end, something I can't justify right now.
Paranoid people may choose to review the source code and build it themselves -- no special tools apart from Visual Studio or compatible IDE like MonoDevelop are required (VS 2017 or newer is preferred).
