### ISSUE TITLE
Complete crash when hitting certain FA posts.

### ISSUE THREAD

**Issue by realwumbl3** [crouvpony47/furdown#16]
![aX0B9eNrk0](https://user-images.githubusercontent.com/69994734/90836075-70d7c600-e31c-11ea-99a2-127be6a67a04.png)

I get this when downloading pages like id 28749873

**Comment by crouvpony47** [comment]
Thank you for spotting this bug out!

I've just released this patch to address it: https://github.com/crouvpony47/furdown/releases/tag/v.0.5.0.1

**Comment by realwumbl3** [comment]
No problem! Thanks for the awesome app. 👍
