### ISSUE TITLE
[Warning] got page, but it doesn't contain any download links.

### ISSUE THREAD

**Issue by ringtailedfox** [crouvpony47/furdown#17]
starting earlier today, whenever I run furdown 0.5.0.1, it doesn't download anything... it lists the submissions, but says this:
Getting page: https://www.furaffinity.net/view/<submission ID#>
[Warning] got page, but it doesn't contain any download links.

Did FurAffinity change something on their end?  or cloudflare?

**Comment by JamieBunpup** [comment]
It seems the fix for this is simple
Download links have changed
They used to be d.facdn.net but they are now d2.facdn.net

**Comment by crouvpony47** [comment]
Fixed in 0.5.0.2

I have no idea if the CDN server change is permanent, so will search for both the old name and the new one. Something like`d3.` will not work though, but anything above 2 resolves to nothing anyway (at the moment, at least)

**Comment by ringtailedfox** [comment]
thanks for the information and update! :D 👍
