### ISSUE TITLE
Downloaded files don't move into their folders

### ISSUE THREAD

**Issue by someonenameguy** [crouvpony47/furdown#18]
So the folder gets made but the files/images just gets placed in the main folder instate of placing them in the folder it made.

**Comment by crouvpony47** [comment]
I couldn't reproduce this bug, could you please elaborate on the details when this happens?

I suppose you've changed the download location or the filename template, yet the old ones are still being used? Please make sure you have saved the changes ("Save and apply" button on the bottom of settings panel; you may need to scroll down a bit to see it), and then try again.

**Comment by someonenameguy** [comment]
Here a video on the the issue.

[Youtube Link](https://youtu.be/ym22NllM0xU)

**Comment by crouvpony47** [comment]
I don't see any bugs on that video, tbh. If you want to put works from different artists in different subfolders, you do that by adjusting the filenames template. The default one `%ARTIST%\%SUBMID%.%FILEPART%` does just that, note the directory separator `\` after `%ARTIST%`.
So in your template you can either replace the `-` after `%ARTIST%` with a `\`, or just prepend `%ARTIST%\` to the template if you like the filename part as is.
Please let me know if this fixes your problem.

**Comment by crouvpony47** [comment]
I don't see any bugs on that video, tbh. If you want to put works from different artists in different subfolders, you do that by adjusting the filenames template. The default one `%ARTIST%\%SUBMID%.%FILEPART%` does just that, note the directory separator `\` after `%ARTIST%`.
So in your template you can either replace the `-` after `%ARTIST%` with a `\`, or just prepend `%ARTIST%\` to the template if you like the filename part as is.
Please let me know if this fixes your problem.

**Comment by someonenameguy** [comment]
Oh ok. That worked. 
Maybe that should be written down somewhere.
Thanks for the help! 👍
