### ISSUE TITLE
[v.0.5.2.0 Bug] Downloading recent submissions only possible one page at a time

### ISSUE THREAD

**Issue by kbgashren** [crouvpony47/furdown#24]
When downloading submissions from the watched artists furdown when submissions are sorted from oldest to newest only downloads the first page (with file number depending on user settings: 24, 48 or 72 submissions). If submissions number is greater than page number, rest of the submissions is not downloaded.

Steps to reproduce:
0. Set Site Settings -> Submission Notifications Order -> Oldest first
1. Submissions inbox have more than 1 page
2. Download submissions by entering Furdown -> Tasks -> link: https://www.furaffinity.net/msg/submissions
3. Click "Go!" button

Result: Only the first page with the number of submissions specified in FA Account settings is downloaded.

Additional info: the same happens if checkbox "updates check mode" is ticked - still only the first page is downloaded.

This is probably due to AppCore.cs expecting only "new@" string being part of the page address - it does not take "old@" into account (line 358 of the code, method CreateSubmissionsListFromGallery).

**Comment by crouvpony47** [comment]
Thank you for this report, I would have probably never discovered this on my own!

[This release](https://github.com/crouvpony47/furdown/releases/tag/v.0.5.3.0) should hopefully fix this bug.



> Additional info: the same happens if checkbox "updates check mode" is ticked - still only the first page is downloaded.

This checkbox allows you to check if any submissions in the list have been sneakily updated - FA has this questionable feature of allowing users to update their submissions without changing almost any metadata associated with them. More details on that [can be found here](https://github.com/crouvpony47/furdown/issues/15). Updates mode doesn't change the way the submissions list is built, so it couldn't have helped in this case.
