### ISSUE TITLE
Downloading folder options

### ISSUE THREAD

**Issue by Callingerio** [crouvpony47/furdown#25]
Is there a way to change how the files are organized? I would like them to all go into a single folder without being put in individual artist folder.

**Comment by crouvpony47** [comment]
Yes, you can change the directory structure by modifying the filename templates.
Note the backslash in the default ones: `%ARTIST%%SCRAPS%\%SUBMID%.%FILEPART%`
To make everything be in one folder, just replace `\` with, say, `-`. If you want the names to match (for the most part) original ones, use `%FILEID%.%FILEPART%`

![](https://i.imgur.com/EZDDK02.jpg)

**Comment by Callingerio** [comment]
It worked! Thanks a ton!
Sorry for the belated response still a little new to this site.
