### ISSUE TITLE
i cant download

### ISSUE THREAD

**Issue by chaimao403** [crouvpony47/furdown#26]
[
![QQ截图20210430122016](https://user-images.githubusercontent.com/40075348/116647939-7529a800-a9ae-11eb-8a51-0a02d2f42117.png)
![QQ截图20210430122044](https://user-images.githubusercontent.com/40075348/116647959-7fe43d00-a9ae-11eb-8d0a-a8451f0e8062.png)

](url)

**Comment by crouvpony47** [comment]
Looks like you have previously downloaded these submissions. By default Furdown keeps track of the previously downloaded files to allow you to remove the unnecessary files (ads and YCH reminders are a good example) without having it re-download all the this removed content on the next pass.

If this is not a desired behaviour, go to the Settings tab, scroll down and uncheck the "Don't download files downloaded before" box; then press "Save and apply".

![изображение](https://user-images.githubusercontent.com/33804948/116650062-1ef63e00-a989-11eb-8e7f-9d58353e8179.png)

**Comment by chaimao403** [comment]
> Looks like you have previously downloaded these submissions. By default Furdown keeps track of the previously downloaded files to allow you to remove the unnecessary files (ads and YCH reminders are a good example) without having it re-download all the this removed content on the next pass.
> 
> If this is not a desired behaviour, go to the Settings tab, scroll down and uncheck the "Don't download files downloaded before" box; then press "Save and apply".
> 
> ![изображение](https://user-images.githubusercontent.com/33804948/116650062-1ef63e00-a989-11eb-8e7f-9d58353e8179.png)
thank you very much


And 
![QQ截图20210430165526](https://user-images.githubusercontent.com/40075348/116672526-e2503400-a9d4-11eb-8a73-f8d8420c4fd7.png)
I have a suggestion that the file name should not be changed after downloading.

**Comment by crouvpony47** [comment]
> I have a suggestion that the file name should not be changed after downloading.

That's possible too. On that same settings tab there's a thing called "Filename template", it determines how to name the files.

If you want to keep it (mostly) original, use something like `%ARTIST%%SCRAPS%\%FILEFULL%`  
I'm saying "mostly" because there is a very small portion of files with broken filenames on the Furaffinity servers, the names for these will not match exactly.
