### ISSUE TITLE
request filename template

### ISSUE THREAD

**Issue by ucok66** [crouvpony47/furdown#3]
Hai is it possible to save images filenames based on the date of its submission (ex. %DATE% or %YEAR%.%MONTH%.%DAY%.%HOUR%.%MINUTE%) and the title of the submission (Spit Roasting Celestia) instead of URL filename (img_20180818_0001_new_new)?

**Comment by crouvpony47** [comment]
It is currently not possible, so I'll take it as a feature request. Shouldn't be too hard to implement though, so I'll consider adding this in the next update.

**Comment by crouvpony47** [comment]
Implemented in [v.0.3.7](https://github.com/crouvpony47/furdown/releases/tag/v.0.3.7.0)

New template thingies:
`%TITLE%` - submission title, stripped of characters that can't be in a filename
`%PDYEAR%`, `%PDMON%`, `%PDDAY%` - publication date
`%PDHOUR%`, `%PDMIN%` - publication time (24h format)

For example, using template
`%ARTIST%\[%PDYEAR%%PDMON%%PDDAY%-%PDHOUR%%PDMIN%] (%SUBMID%) %TITLE%.%EXT%`
you'll get
`voxell\[20170715-1707] (24158730) Horsin' around.png` for submission №24158730. Using `%SUBMID%` is of course not mandatory, as long as no two submissions have exactly the same name and the publication time within one minute.
