### ISSUE TITLE
Feature Request - Option to grab URLs of images without downloading.

### ISSUE THREAD

**Issue by KevanAwesome** [crouvpony47/furdown#30]
A mode to grab the URL of the images from FurAffinity database[d.furaffinity.net].

**Comment by KevanAwesome** [comment]
Into like a txt file; as the program already shows the links in the cmd prompt.

**Comment by crouvpony47** [comment]
This is something that you can easily make a hack for.

A proper GUI option would be nice, but at this point the app depends on so many things that are either already obsolete (or getting dangerously close) for its UI that this entire part needs to be rewritten anyway. 

As for the hack, in `CoreApp.cs`, find a block starting with

    using (var response = await http.GetAsync(sp.URL.Replace("?", "%3F"), HttpCompletionOption.ResponseHeadersRead))

that `sp.URL.Replace("?", "%3F")` is the URL. Assuming you just want every URL written to a single large file, just replace the entire `using` contents with something like:

    File.AppendAllText("urls.txt", sp.URL.Replace("?", "%3F") + Environment.NewLine);

**Comment by KevanAwesome** [comment]
Ok.
