### ISSUE TITLE
Warning :: cannot parse date :: String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by ucok66** [crouvpony47/furdown#4]
```
Auth check completed successfully.
Building submissions list for https://www.furaffinity.net/gallery/holivi
Getting page: https://www.furaffinity.net/gallery/holivi/1
Getting page: https://www.furaffinity.net/gallery/holivi/2
Getting page: https://www.furaffinity.net/gallery/holivi/3
Reached an empty page. Total elements found: 134
Saving submissions list...
Submissions list saved to "latest_subs.log"
Processing submissions list...
> Processing submission #29924294
Getting page: https://www.furaffinity.net/view/29924294
Title: Rarity
Warning :: cannot parse date :: String was not recognized as a valid DateTime.
target filename: furaffinity\2020_01_01_21_19_Rarity.jpg
Downloading: https://d.facdn.net/download/art/holivi/1546254701/1546254701.holivi_???_???????.jpg
Done: #29924294
```
I don't know if that download link supposed to have many question mark is a bug, but it downloaded the images perfectly

**Comment by crouvpony47** [comment]
Question marks are not a bug, the filename contains Cyrillic characters that are either not part of your console codepage, or not present in the font used. In any case this won't affect saving the file properly.

As for the main issue, I couldn't immediately reproduce the problem on my setup, the date appears to be parsed properly. I would appreciate your help in figuring out what's wrong, though.

For that I need the following:
1. furdown version
2. the log from this special build - http://www.mediafire.com/file/p4ejux2vfcqk60b/furdown0400test.exe (it will have one extra line after the warning)
3. the line containing the text "popup_date" in the source of the page https://www.furaffinity.net/view/29924294 as it appears to you. For example, for me it's `<strong><span title="Dec 31, 2018 03:11 PM" class="popup_date">a year ago</span></strong>`
4. your language/locale (something like "en-UK")

**Comment by ucok66** [comment]
I was using the release version (0.4.0.0) for the issue. the filename setting look like this `furaffinity\%PDYEAR%_%PDMON%_%PDDAY%_%PDHOUR%_%PDMIN%_%TITLE%.%EXT%`

furdown0400test.exe log:
```
furdown 0.4.0.0
<crouvpony47.itch.io> <github.com/crouvpony47>
Checking authorization...
Found cookies: ***
Auth check completed successfully.
Building submissions list for https://www.furaffinity.net/gallery/holivi
Getting page: https://www.furaffinity.net/gallery/holivi/1
Getting page: https://www.furaffinity.net/gallery/holivi/2
Getting page: https://www.furaffinity.net/gallery/holivi/3
Reached an empty page. Total elements found: 134
Saving submissions list...
Submissions list saved to "latest_subs.log"
Processing submissions list...
> Processing submission #29924294
Getting page: https://www.furaffinity.net/view/29924294
Title: Rarity
Warning :: cannot parse date :: String was not recognized as a valid DateTime.
Info :: date string :: a year ago
target filename: furaffinity\2020_01_02_03_44_Rarity.jpg
Downloading: https://d.facdn.net/download/art/holivi/1546254701/1546254701.holivi_???_???????.jpg
Done: #29924294
```
It said `Info :: date string :: a year ago`, but the date for the filename is still wrong.

I still use same setting for the filename (`furaffinity\%PDYEAR%_%PDMON%_%PDDAY%_%PDHOUR%_%PDMIN%_%TITLE%.%EXT%`)

I use en_US for the language

**Comment by crouvpony47** [comment]
I was able to reproduce this issue by setting non-default option "Full date format" in the account settings. [v.0.4.1](https://github.com/crouvpony47/furdown/releases/tag/v.0.4.1.0) should fix this, so the submission date is parsed properly in both full date mode and in the fuzzy one. If it's not, feel free to reopen this issue.
