### ISSUE TITLE
save htm descriptions doesn't seem to work

### ISSUE THREAD

**Issue by electricdl42** [crouvpony47/furdown#40]
i have been trying to archive a large number of galleries and haven't been able to get any of the submission descriptions to save.

**Comment by AudunVN** [comment]
Downloading descriptions *seems* to be working fine for me on version 0.5.4.0. Not saying that there isn't an issue here, only that I haven't been able to reproduce it yet after downloading a gallery just now.

Are the description files not being saved at all, with no error messages anywhere?

If you're up for sharing a link to a gallery/submission that Furdown doesn't save a description for and a screenshot/summary of your settings (maybe particularly the `Description filename template` field) and some log output, that'd probably help a fair bit with figuring out what might be going on here.

---

PS: Remembered I've got a gallery with one entire pretty normal photo (with a description and everything!) that I'm not too worried about people seeing at https://www.furaffinity.net/gallery/space.northpaw/ that could work alright as a test.

Console output and description HTML file included below for reference.

![image](https://github.com/user-attachments/assets/393c46a6-2475-41d1-9b0b-16f1161743e7)

```html
<div class="submission-description-container link-override">
                        <div class="submission-title">
                            <h2 class="submission-title-header">Spring Taiga</h2>
                            Posted <strong><span title="Jun 24, 2017 05:48 PM" class="popup_date">Jun 24, 2017 05:48 PM</span></strong>
                        </div><hr><div class="submission-description user-submitted-links">
                    Quick first test upload; description's subject to change. Haven't used FA in a while, gonna try migrate some of my furrier photography and stuff over here from 500px and DA.
                                    </div>
            </div>
```

**Comment by electricdl42** [comment]
update, just started working with single galleries, it appears that this is only an issue with downloading multiple galleries via the links list feature. there are no error messages in the console, and when downloading a single gallery, the description comes through perfectly. 
![debug](https://github.com/user-attachments/assets/06a4f556-82f5-4dd4-93fd-205d0278fd5e)

**Comment by crouvpony47** [comment]
@electricdl42, I've tried reproducing this issue, but for me it appears to be working for both single URLs and for the links lists.
Please make sure you have `[v] also save .htm descriptions` ticked when trying to download a links list. If it still fails, could you please provide a minimal example of the list file which triggers the problem? (for testing you may need to disable `[ ] Don't download files downloaded before` in settings)

**Comment by electricdl42** [comment]
sorry for not responding for a while, but i have fixed my issue, i removed all prior download directories and the furdown folder in user/appdata/roaming. after this, the download worked correctly.
