### ISSUE TITLE
11/10 Program

### ISSUE THREAD

**Issue by K9Paradox** [crouvpony47/furdown#6]
Hi, I saw you updated your program to now work with favorites extremely fast, and I'm glad that you are paying that close attention to this project. I had a question though since there is no way to normally comment on your project, unfortunately, it is being listed as a "issue". Is there a present way to have the files downloaded not put into Artist Folders. I.E. just one folder full of all the images instead of filtered to each artist. If there is please comment back :). If not, then that's fine, I hope you have a great day. And thank you for the speedy update! <3

**Comment by crouvpony47** [comment]
I'm very happy to see other people using this program as well :3

Yes, you can dump everything in one folder. Switch over to the *Settings* tab and remove `%ARTISTS%\` part from the *filename* and *description filenames* templates (or just replace the backslash with some other character, such as whitespace); then click on *Save and apply*.

![](https://i.imgur.com/2szMUdr.png)

I'll be closing this issue then, but if you have other questions you ofc can reopen it or create another one.
