### ISSUE TITLE
Save .htm descriptions Startindex error

### ISSUE THREAD

**Issue by JAK0723** [crouvpony47/furdown#7]
Whenever I try to download something I with the "also save .htm descriptions" option ticked, I get the following error:
```
Startindex cannot be less than zero.
Parameter name: startindex
```
This happens with any user gallery, e.g. `https://www.furaffinity.net/gallery/dragoneer/`.

**Comment by crouvpony47** [comment]
I couldn't reproduce this behaviour on the latest version of the app, 0.4.2.0. Which version are you trying to use?

It is also possible that you use a weird non-standard account setting that breaks the parser. To check that, please navigate to any submission page that fails to get parsed (i.e. `https://www.furaffinity.net/view/{some-valid-number}/`) in your browser, and copy its source (`Ctrl+U` in most browsers) as a file attachment here, or to a site like pastebin, posting a link here. This page doesn't contain much sensitive data, but if you don't want your username known, you can just censor it - that's not what I'll looking for anyway.

**Comment by crouvpony47** [comment]
Okay, this issue is reproducible using the really old 0.3.6.0 build. Furaffinity has changed a few things since then, so any version before 0.4.2.0 is considered unstable. Please update to the most recent build and tell me whether or not the issue still persists for you.

**Comment by JAK0723** [comment]
I thought I was using the latest version but I must have been wrong. I downloaded the latest exe and it seems to be working fine now. Thanks for the help.
